const screens = {
  login: "LOGIN",
  register: "REGISTER",
  home: "HOME",
  productList: "PRODUCT_LIST",
  explore: "EXPLORE",
  account: "ACCOUNT",
  cart: "CART",
  main: "MAIN",
  profile: "PROFILE",
  settings: "SETTINGS",
  onBoarding: "ON_BOARDING",
  welcome: "WELCOME",
  productDetails: "PRODUCT_DETAILS",
  orderSummery: "ORDER_SUMMERY",
  successScreen: "SUCCESS_SCREEN",
  orderSummeryShipping: "ORDER_SUMMERY_SHIPPING",
  payment: "PAYMENT",
  search: "SEARCH",
  myOrder: "MY_ORDER_LIST",
  webView: "WEB_VIEW",
  helpCenter: "HELP_CENTER",
  splash: "SPLASH",
  notification: "NOTIFICATION",
};
export default screens;
